version: "3.7"

services:
  matomo-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'db'
      MYSQL_DATABASE: 'matomo'
    volumes:
      - matomo-db:/var/lib/mysql
    networks:
      - matomo-network

  matomo:
    image: matomo:fpm
    links:
      - db
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
    environment:
      MATOMO_DATABASE_USERNAME: 'root'
      MATOMO_DATABASE_PASSWORD: 'db'
      MATOMO_DATABASE_DBNAME: 'matomo'
    networks:
      - matomo-network

  matomo-web:
    image: nginx:alpine
    restart: always
    tty: true
    environment:
      VIRTUAL_HOST: analytics.fleigm.de
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: analytics.fleigm.de
      LETSENCRYPT_EMAIL: admin@fleigm.de
    expose:
      - 80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
    networks:
      - matomo-network
      - nginx-proxy

volumes:
  matomo-db:

networks:
  matomo-network:
    driver: bridge
  nginx-proxy:
    external: true
    name: nginx-proxy